/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.subhranil.jsonhandler;

import com.subhranil.jsonhandler.utils.Library;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
        System.out.println(classUnderTest.someLibraryMethod());
    }
}
